### ISSUE TITLE
Running youtube-dl doesn't work on windows

### ISSUE THREAD

**Issue by comp500** [mswift42/nip#1]
```
exec: "/bin/sh": file does not exist
exec: not started
```

Windows doesn't have /bin/sh, so it can't exec youtube-dl. You could try executing youtube-dl directly, without using the shell, e.g. `exec.Command("youtube-dl", "-f", format, u)` in [cl.go](https://github.com/mswift42/nip/blob/master/cl/cl.go#L198).
exec.Command uses LookPath to find the executable, so using /bin/sh should not be required on any system.

**Comment by mswift42** [comment]
Thanks, I've completely missed download commands for windows.

Could you please try again with the updated version, I hope I've fixed it now.

**Comment by comp500** [comment]
Downloading programmes works very well on windows now. However, the formats command is broken in [this line](https://github.com/mswift42/nip/blob/1c95e33a8c1de496ba23af279d42fc3bab5d9b1f/cl/cl.go#L261), it should use `/c` instead of `-c`.

**Comment by mswift42** [comment]
Thanks, good catch. It's fixed now.

**Comment by comp500** [comment]
Thanks. I haven't found any further problems with it, so I'll close this issue.

**Comment by mswift42** [comment]
Thanks, You have been very helpful.
