### ISSUE TITLE
Opening webpages doesn't work on windows

### ISSUE THREAD

**Issue by comp500** [mswift42/nip#2]
The start command is required to open a webpage. In [cl.go](https://github.com/mswift42/nip/blob/eee80da851f09efc56bde6f1cf2cd9604234a2e3/cl/cl.go#L116), `exec.Command("cmd", "/c", url)` should be `exec.Command("cmd", "/c", "start", url)`.

**Comment by mswift42** [comment]
Thank you.

Fixed with [37ff03a](]https://github.com/mswift42/nip/commit/37ff03afbc2118dc8645e8498b5312869d98bcc9).
